### PR TITLE
tree: Add Pivot Key

### PR DESCRIPTION
**Pull request by jwuensche**
> Dependencies: #29 #32 

This PR adds PivotKeys.

Changes are described in #29, basic tests have been implemented and the LFU migration policy has been modified to use these new keys. Therefore, deprecating the use of `DiskOffsets` in the node identification process.

### CODE REVIEW

**Comment by jwuensche** [comment]
Manually deleted caches, as they contained outdated versions of the git based reference to the rework of the lfu-cache.

**Comment by jwuensche** [comment]
All the checks pass now, pending on https://github.com/julea-io/lfu-cache/pull/1 to fix the lfu-cache dependency with a new version.

**Review by SajadKarim — COMMENTED** [review]
Reviewed the change.

**Review by SajadKarim — APPROVED** [review]
Reviewed.

**Pull request merged**
